"""Version_0000

Revision ID: 0a21eba4096a
Revises: 
Create Date: 2017-08-17 00:01:52.811113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a21eba4096a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_password', table_name='user')
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.create_index('ix_user_password', 'user', ['password'], unique=False)
    # ### end Alembic commands ###
