"""Version_0010

Revision ID: 0a9a850524f2
Revises: b6948e454645
Create Date: 2017-09-05 14:04:55.652721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9a850524f2'
down_revision = 'b6948e454645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notices_title', table_name='notices')
    op.create_index(op.f('ix_notices_title'), 'notices', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notices_title'), table_name='notices')
    op.create_index('ix_notices_title', 'notices', ['title'], unique=False)
    # ### end Alembic commands ###
