"""Version_0001

Revision ID: 127e03ca97fa
Revises: 0a21eba4096a
Create Date: 2017-08-17 00:03:33.607079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127e03ca97fa'
down_revision = '0a21eba4096a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_password', table_name='user')
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.create_index('ix_user_password', 'user', ['password'], unique=1)
    # ### end Alembic commands ###
