"""Version_0007

Revision ID: 1e909361af25
Revises: 3ebdb8e34eb7
Create Date: 2017-08-29 14:53:11.011307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e909361af25'
down_revision = '3ebdb8e34eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('content', sa.String(length=1024), nullable=True),
    sa.Column('species', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_author'), 'notices', ['author'], unique=False)
    op.create_index(op.f('ix_notices_content'), 'notices', ['content'], unique=True)
    op.create_index(op.f('ix_notices_species'), 'notices', ['species'], unique=False)
    op.create_index(op.f('ix_notices_title'), 'notices', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notices_title'), table_name='notices')
    op.drop_index(op.f('ix_notices_species'), table_name='notices')
    op.drop_index(op.f('ix_notices_content'), table_name='notices')
    op.drop_index(op.f('ix_notices_author'), table_name='notices')
    op.drop_table('notices')
    # ### end Alembic commands ###
