"""Version_0003

Revision ID: 2502bf5f8f80
Revises: 8c77ffb96b0f
Create Date: 2017-08-17 02:23:48.202949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2502bf5f8f80'
down_revision = '8c77ffb96b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_password', table_name='user')
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.create_index('ix_user_password', 'user', ['password'], unique=1)
    # ### end Alembic commands ###
