"""Version_0006

Revision ID: 3ebdb8e34eb7
Revises: 866551b68d82
Create Date: 2017-08-21 23:48:15.202527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ebdb8e34eb7'
down_revision = '866551b68d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('old_email', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('old_password', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('old_phone', sa.String(length=11), nullable=True))
    op.add_column('user', sa.Column('old_section', sa.String(length=6), nullable=True))
    op.add_column('user', sa.Column('old_user_img', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'old_user_img')
    op.drop_column('user', 'old_section')
    op.drop_column('user', 'old_phone')
    op.drop_column('user', 'old_password')
    op.drop_column('user', 'old_email')
    # ### end Alembic commands ###
