"""Version_0005

Revision ID: 866551b68d82
Revises: 1b356097d81b
Create Date: 2017-08-21 01:03:53.143224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866551b68d82'
down_revision = '1b356097d81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_img', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_img')
    # ### end Alembic commands ###
