"""Version_0002

Revision ID: 8c77ffb96b0f
Revises: 127e03ca97fa
Create Date: 2017-08-17 00:40:34.511770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c77ffb96b0f'
down_revision = '127e03ca97fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.drop_index('ix_user_password', table_name='user')
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.create_index('ix_user_password', 'user', ['password'], unique=False)
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    # ### end Alembic commands ###
