"""Version_0008

Revision ID: 9fc14956130f
Revises: 1e909361af25
Create Date: 2017-08-29 15:16:17.760540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc14956130f'
down_revision = '1e909361af25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('create_date', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_notices_create_date'), 'notices', ['create_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notices_create_date'), table_name='notices')
    op.drop_column('notices', 'create_date')
    # ### end Alembic commands ###
