"""Version_0009

Revision ID: b6948e454645
Revises: 9fc14956130f
Create Date: 2017-08-31 09:05:13.442003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6948e454645'
down_revision = '9fc14956130f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notices_content', table_name='notices')
    op.create_index(op.f('ix_notices_content'), 'notices', ['content'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notices_content'), table_name='notices')
    op.create_index('ix_notices_content', 'notices', ['content'], unique=1)
    # ### end Alembic commands ###
